# Generated by Django 3.2 on 2021-08-21 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=60, unique=True)),
                ('startTime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('payoutTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('payAmount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('receiverWalletAddress', models.CharField(max_length=200)),
                ('receiverEmail', models.EmailField(max_length=200)),
                ('creatorName', models.CharField(max_length=200)),
                ('creatorEmail', models.EmailField(max_length=200)),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Accepted'), (2, 'Cancelled'), (3, 'Done')])),
                ('version', models.IntegerField()),
            ],
        ),
    ]
