# Generated by Django 3.2 on 2021-08-15 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_alter_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=40, unique=True)),
                ('startTime', models.DateTimeField()),
                ('payoutTime', models.DateTimeField()),
                ('Duration', models.JSONField()),
                ('Terms', models.TextField()),
                ('Condition', models.TextField()),
                ('Fee', models.DecimalField(decimal_places=5, max_digits=20)),
                ('Location', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=200)),
                ('Attachments', models.FilePathField()),
                ('generatedCode', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Editing'), (2, 'Ongoing'), (3, 'Payed')])),
                ('updateTime', models.DateTimeField()),
                ('createTime', models.DateTimeField()),
                ('version', models.IntegerField()),
                ('Receivers', models.ManyToManyField(to='User.User')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='User.user')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to='User.user')),
            ],
        ),
    ]
