# Generated by Django 3.2 on 2021-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartContract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcontract',
            name='eventName',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
