# Generated by Django 3.2 on 2021-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=3, max_digits=3)),
                ('profession', models.CharField(max_length=30)),
                ('userType', models.SmallIntegerField(choices=[(0, 'Admin'), (1, 'Promoter'), (2, 'Performer')])),
                ('publicKey', models.CharField(max_length=50)),
            ],
        ),
    ]
