FROM node:lts-alpine

WORKDIR /app

RUN npm install -g ganache-cli

CMD [\
  "ganache-cli", \
  "-h", "0.0.0.0", \
  "--deterministic", "--db=/ganache_data", \
  "--deterministic", \
  "--mnemonic", "tonight surface whale legend urban unaware void undo oak clean crane amount" \
  ]