FROM node:lts-alpine

WORKDIR /app

RUN npm install -g ganache-cli

CMD [\
  "ganache-cli", \
  "-h", "0.0.0.0", \
  "--deterministic", "--db=/ganache_data", \
  "--deterministic", \
  "--mnemonic", "grant luggage banana roast girl cross weird tornado affair genius tourist swamp" \
  ]
