
### --- BASE IMAGE --- ###
FROM node:lts-alpine

### --- ENVIRONMENT --- ###
ENV VERSION "0.1"
ENV COMMAND "migrate"
ENV API_HOST "0.0.0.0"
ENV API_PORT "8888"
ENV NETWORK "development"
ENV SRC_DIR "/app"
# ENV GIT_BRANCH "master"
# ENV GIT_FOLDER "/"
ENV TRUFFLE_VERSION "5.3.3"

### --- SETUP --- ###
RUN npm install -g truffle@$TRUFFLE_VERSION && npm config set bin-links false

RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR

COPY contracts ./contracts
COPY migrations ./migrations
COPY test ./test
COPY truffle-config.js ./truffle-config.js

EXPOSE $API_PORT

RUN npm install -g truffle
CMD ["npm", "run", "./scripts"]
