# # Install our base image
# # lts = long-term support, i.e. the latest stable version of Node
# #       specifically, Node's LTS version is currently 14.16.1 (April 2021)
# # alpine = Alpine Linux, the minimal Linux image: https://hub.docker.com/_/alpine
# FROM node:lts-alpine

# # The WORKDIR instruction sets the working directory for any
# # RUN, CMD, ENTRYPOINT, COPY and ADD instructions that follow
# # it in the Dockerfile. If the WORKDIR doesn’t exist, it will
# # be created even if it’s not used in any subsequent Dockerfile
# # instruction.
# WORKDIR '/app'

# RUN npm install -g --save ganache-cli

# EXPOSE 8545

# # ENTRYPOINT [ "testrpc" ]

# CMD ["ganache-cli"]

# Original author: github/gjeanmart
# Source: https://github.com/gjeanmart/truffle-docker

### --- BASE IMAGE --- ###
FROM node:lts-alpine

### --- ENVIRONMENT --- ###
ENV VERSION "0.1"
ENV COMMAND "migrate"
ENV API_HOST "0.0.0.0"
ENV API_PORT "8888"
ENV NETWORK "development"
ENV SRC_DIR "/app"
# ENV GIT_BRANCH "master"
# ENV GIT_FOLDER "/"
ENV TRUFFLE_VERSION "5.3.3"

### --- SETUP --- ###
RUN npm install -g truffle@$TRUFFLE_VERSION && npm config set bin-links false

RUN mkdir -p $SRC_DIR

EXPOSE $API_PORT
WORKDIR $SRC_DIR

RUN npm install -g truffle
RUN npm install
RUN ./scripts/api.js